[package]
name = "gki-lkm-patcher"
description = "A simple LKM patcher via WebAssembly"
repository = "https://github.com/ZakoDaNiuMask/ZakoDaNiuMask.github.io"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
regex-lite = "0.1"
android-bootimg = { git = "https://github.com/5ec1cff/android_bootimg", rev = "150425b027c76ea104c82e408571651f2181b2c2" }
js-sys = "0.3"
wasm-bindgen = "0.2"

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
overflow-checks = false
